# Generated by Django 4.1.7 on 2023-02-27 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='name')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.category', verbose_name='parent')),
            ],
        ),
    ]
